### ISSUE TITLE
archive cleaner should remove the sources of the package too

### ISSUE THREAD

**Issue by Bluewind** [archlinux/archivetools#3]
The archive cleaner currently only removes the package files, but we also have copies of the sourceballs. These should be removed too.

**Comment by jelly** [comment]
We started adding source archives in [2016](https://github.com/archlinux/archivetools/commit/41909d4d89c35dd06771279fa9916d35d838e204). The logic should be to remove a source package if the package is not required anymore, an addition to the currenct cleaning script.

Since we already have cleaned up packages before we also need a script to remove sources for packages which where already removed.

**Comment by Bluewind** [comment]
I've created the removal script for 2016 and ran it so this issue now only needs to deal with removal of sourceballs during the removal of packages.
